### ISSUE TITLE
publishFeatureType: Trying to create new feature type inside the store, but no attributes were specified

### ISSUE THREAD

**Issue by cesco69** [meggsimum/geoserver-node-client#113]
```ts
import { GeoServerRestClient } from 'geoserver-node-client';
const gs = new GeoServerRestClient('http://localhost/geoserver/rest/');

const nativeBoundingBox = {
    minx: 8.15,
    maxx: 8.16,
     miny: 50.0,
    maxy: 50.1,
    crs: {
        '@class': 'projected',
        $: 'EPSG:4326'
    }
};
const wsStoreName = 'xyz';
const ftName = 'doc';
await gs.layers.publishFeatureType(wsStoreName , wsStoreName , ftName , ftName , ftName , 'EPSG:4326', true, null, nativeBoundingBox);
```

error:

```
Trying to create new feature type inside the store, but no attributes were specified
```

how specifie attributes ?

**Comment by JakobMiksch** [comment]
Maybe the examples from the tests help you. Like this one: https://github.com/meggsimum/geoserver-node-client/blob/master/test/test.js#L350-L373

The error message from GeoServer are often not very helpful. 

If you cannot create your feature type with this library, you can try to send the REST request directly with tools like Postman or curl.

In general it would be useful to get more information about your problem, like what kind of store you are using.
