### ISSUE TITLE
Add optional param 'nativeBoundingBox' to LayerClient.publishFeatureType

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/geoserver-node-client#23]
Add optional parameter `nativeBoundingBox` to `LayerClient.publishFeatureType` since it is necessary to provide a bounding box in case the data store is empty at FeatureType creation time. Otherwise an exception is thrown.

**Comment by JakobMiksch** [comment]
This is really important. I had the same issue in an different context as well.
