### ISSUE TITLE
Interest in publishing as a lib?

### ISSUE THREAD

**Issue by weskamm** [meggsimum/geoserver-node-client#27]
I would like to use this nice work as a dependency in another node based project.
It would be nice to have a published version on e.g. npm.
I could care about preparing the code for this. 
What do you think?

**Comment by chrismayer** [comment]
Hi @weskamm, 
yes good idea to publish this as lib on npm. Currently we are using this in other node projects via `"geoserver-node-client": "https://github.com/meggsimum/geoserver-node-client.git#master",` in the `dependency` section of the `package.json`.

But using it by npm directly would be more convenient and therefore attract more people.

It would be very much appreciated if you could prepare this :+1:

**Comment by weskamm** [comment]
Great!
I already opened the can of worms and added babel et al., but i just realized that its way less work when just using or enforcing nodev14 and up, so we do not need to transpile at all.
So it should be just a matter of adding packagin / release stuff to the package.json.
I think i will come up with a PR soon.

"Some" dude already got the package registered ^^
https://www.npmjs.com/package/geoserver-rest-client

but it looks like https://www.npmjs.com/package/geoserver-node-client is still available..

**Comment by weskamm** [comment]
Ok just added a simple way using release-it:
https://github.com/meggsimum/geoserver-node-client/pull/28

It enables interactive releases from commandline, pushing to npm and github.
Not 100% sure if configuration is complete, will need a real release to tell i guess :-)

**Comment by JakobMiksch** [comment]
@weskamm thanks for you PR. 
After some initial setup it worked like a charm :smile: 

A first release has been published to npm https://www.npmjs.com/package/geoserver-node-client and also to GitHub

Does this work for you?

**Comment by weskamm** [comment]
Yes, thanks for your work, seems to work as expected!

**Comment by JakobMiksch** [comment]
@weskamm great to hear and thanks for your effort initiating the automatic release. I guess there is still some potential to streamline the release process. This will be addressed a new PR.
