### ISSUE TITLE
No exception for expectable HTTP 404 in GET requests

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/geoserver-node-client#74]
There are often cases you request an object via HTTP GET - e.g. a layer - in order to check its existence and create it afterwards if not existing. So the HTTP 404 in the GET request is not an exception. It is an expected result, which should be handled differently than raising an exception.

First suggestion as base for a discussion: Adding a flag (`notFoundIsOk` or similar) to all GET requests, where it might make sense. If an HTTP 404 occurs and the flag is set to true no exception should be raised. Maybe an info log or even something smarter could happen. Default for the flag should be false, to sustain to current behavior.

/cc @JakobMiksch

**Comment by JakobMiksch** [comment]
Since the version 1.0., expected 404 request are catched. Then undefined is returned. Here an example: https://github.com/meggsimum/geoserver-node-client/blob/1.1.0/src/layer.js#L22-L60
Does this solve the issue?

**Comment by chrismayer** [comment]
Yes, that should solve the issue....thanks. Going to close this now.
